const DATA={'ชุด 1':window.OOP_SET_1,'ชุด 2':window.OOP_SET_2,'ชุด 3':window.OOP_SET_3};
const L=['A','B','C','D'];
let setName=localStorage.getItem('oop_set')||'ชุด 1',part='mcq',submitted=false,ans={},wa={},codeAns={},runOutputs={};
let pyodide=null,pyodideLoading=null;
const $=s=>document.querySelector(s),key=x=>'oop_'+setName+'_'+x;
function load(){try{ans=JSON.parse(localStorage.getItem(key('a'))||'{}');wa=JSON.parse(localStorage.getItem(key('w'))||'{}');codeAns=JSON.parse(localStorage.getItem(key('code'))||'{}');runOutputs=JSON.parse(localStorage.getItem(key('runs'))||'{}')}catch{ans={};wa={};codeAns={};runOutputs={}}submitted=localStorage.getItem(key('sub'))==='1'}
function save(){localStorage.setItem(key('a'),JSON.stringify(ans));localStorage.setItem(key('w'),JSON.stringify(wa));localStorage.setItem(key('code'),JSON.stringify(codeAns));localStorage.setItem(key('runs'),JSON.stringify(runOutputs))}
function norm(t){return String(t||'').toLowerCase().replace(/<[^>]+>/g,' ').replace(/[^a-z0-9ก-๙().='_]+/gi,' ').replace(/\s+/g,' ').trim()}
const ALIAS={'instance attribute':['instance attribute','object property','property ของ object'],'class attribute':['class attribute','attribute ของ class'],shadow:['shadow','บัง','ทับ'],lookup:['lookup','หา attribute'],'same object':['same object','object เดียวกัน'],reference:['reference','อ้างถึง'],alias:['alias','ตัวแปรอีกชื่อ'],method:['method','เมธอด'],instance:['instance','object'],property:['property','attribute'],modify:['modify','แก้','เปลี่ยนค่า'],'delete property':['delete property','ลบ property'],'delete object':['delete object','ลบ reference'],'two objects':['two objects','2 objects','สอง object']};
function hit(t,c){let n=norm(t),xs=ALIAS[c]||[c];return xs.some(x=>n.includes(norm(x)))}
function grade(q,t){t=String(t||'').trim();const cs=q.concepts||[];if(!t)return{score:0,label:'ยังไม่ตอบ',m:[],miss:cs};const m=cs.filter(c=>hit(t,c)),miss=cs.filter(c=>!m.includes(c));const cov=cs.length?m.length/cs.length:1,len=Math.min(1,norm(t).length/140),reason=/(เพราะ|ดังนั้น|จึง|ทำให้|because|therefore|เนื่องจาก|หมายความว่า)/i.test(t)?1:0;let score=Math.round(100*(.72*cov+.16*len+.12*reason));if(norm(t).length<20)score=Math.min(score,45);return{score,label:score>=85?'ครบถ้วนมาก':score>=65?'ถูกหลัก แต่ยังขาดบางส่วน':score>=40?'ได้บางส่วน':'ยังไม่เพียงพอ',m,miss}}
function badge(g){return `<div class="grade"><b>${g.label} — ${g.score}%</b>${g.m.length?`<div>พบ: ${g.m.join(' • ')}</div>`:''}${g.miss.length?`<div style="color:var(--muted)">ยังขาด: ${g.miss.join(' • ')}</div>`:''}</div>`}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function mc(q){return `<section class="card" id="q${q.id}"><div class="qhead"><b>ข้อ ${q.id}</b><span>${q.topic} · ${q.difficulty}</span></div><div class="prompt">${q.prompt}</div><div class="options">${q.options.map((o,i)=>`<label class="option ${submitted?(i===q.answer?'correct':ans[q.id]===i?'wrong':''):''}"><input type="radio" name="q${q.id}" value="${i}" ${ans[q.id]===i?'checked':''} ${submitted?'disabled':''}><b>${L[i]}.</b><span>${o}</span></label>`).join('')}</div>${submitted?`<div class="solution"><b>เฉลย ${L[q.answer]}</b><br>${q.explanation}</div>`:''}</section>`}
function wr(q){const g=submitted?grade(q,wa[q.id]):null;return `<section class="card" id="q${q.id}"><div class="qhead"><b>ข้อ ${q.id}</b><span>${q.topic} · ${q.difficulty}</span></div><div class="written-question"><span class="label">โจทย์</span><div class="prompt">${q.prompt}</div></div><div style="margin-top:12px"><b>โค้ด Python</b><textarea class="code-editor" data-code-id="${q.id}" placeholder="# เขียนโค้ด Python ที่นี่...">${codeAns[q.id]||''}</textarea></div><div style="margin-top:12px"><b>คำตอบ / คำอธิบาย</b><textarea data-exp-id="${q.id}" ${submitted?'readonly':''} placeholder="อธิบายด้วยคำของคุณเอง...">${wa[q.id]||''}</textarea></div>${submitted?badge(g)+`<div class="solution"><b>แนวคำตอบ</b><br>${q.solution}</div>`:''}</section>`}
function render(){const current=DATA[setName];if(!current){$('#title').textContent='โหลดข้อมูลข้อสอบไม่สำเร็จ';$('#qs').innerHTML='<section class="card">ไม่พบข้อมูล '+esc(setName)+'</section>';return}$('#title').textContent='Python OOP — '+setName;const qs=current[part]||[];$('#qs').innerHTML='<h2>'+(part==='mcq'?'PART A — Multiple Choice':'PART B — Written / Programming')+'</h2>'+qs.map(q=>part==='mcq'?mc(q):wr(q)).join('');bind();nav();prog()}
function bind(){document.querySelectorAll('input[type=radio]').forEach(x=>x.onchange=()=>{ans[+x.name.slice(1)]=+x.value;save();prog();nav()});document.querySelectorAll('[data-exp-id]').forEach(x=>x.oninput=()=>{wa[+x.dataset.expId]=x.value;save();prog();nav()});document.querySelectorAll('[data-code-id]').forEach(x=>x.oninput=()=>{codeAns[+x.dataset.codeId]=x.value;save();prog();nav()})}
function nav(){const current=DATA[setName];if(!current)return;const all=[...current.mcq,...current.written];$('#nav').innerHTML=all.map(q=>{const d=q.id<=20?ans[q.id]!==undefined:((wa[q.id]||'').trim()||(codeAns[q.id]||'').trim());return `<button class="${d?'done':''}" onclick="go(${q.id})">${q.id}</button>`}).join('')}
function go(id){part=id<=20?'mcq':'written';tabs();render();setTimeout(()=>$('#q'+id)?.scrollIntoView({behavior:'smooth'}),20)}
function prog(){const current=DATA[setName];if(!current)return;const a=current.mcq.filter(q=>ans[q.id]!==undefined).length,w=current.written.filter(q=>(wa[q.id]||'').trim()||(codeAns[q.id]||'').trim()).length;$('#progTxt').textContent=`${a+w}/25 (MCQ ${a}/20 • Written ${w}/5)`;$('#bar').style.width=((a+w)/25*100)+'%'}
function tabs(){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.part===part))}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{part=b.dataset.part;tabs();render()});$('#setSel').value=setName;$('#setSel').onchange=e=>{setName=e.target.value;localStorage.setItem('oop_set',setName);part='mcq';load();tabs();render()};
async function ensurePyodide(btn){if(pyodide)return pyodide;if(pyodideLoading)return pyodideLoading;pyodideLoading=(async()=>{if(!window.loadPyodide)throw new Error('โหลด Python runtime ไม่สำเร็จ');pyodide=await loadPyodide();return pyodide})();return pyodideLoading}
function unsafe(code){return /\b(import|open|eval)\b/.test(code)?'คำสั่งนี้ไม่อนุญาตใน Test Runner':null}
$('#submit').onclick=()=>{if(!submitted){if(!confirm('ส่งข้อสอบและเปิดเฉลยหรือไม่?'))return;submitted=true;localStorage.setItem(key('sub'),'1');render()}const current=DATA[setName];if(!current)return;const c=current.mcq.reduce((s,q)=>s+(ans[q.id]===q.answer),0);$('#score').innerHTML=`<h2>${setName}</h2><p><b>ปรนัย:</b> ${c}/20</p>`;scoreDlg.showModal()};
$('#reset').onclick=()=>{if(!confirm('ล้างคำตอบชุดนี้?'))return;['a','w','code','runs','sub','exacttests'].forEach(x=>localStorage.removeItem(key(x)));ans={};wa={};codeAns={};runOutputs={};submitted=false;render()};
$('#copy').onclick=async()=>{const t=(DATA[setName]?.written||[]).map(q=>`ข้อ ${q.id}\nCODE:\n${codeAns[q.id]||'(ไม่มี)'}\n\nคำอธิบาย:\n${wa[q.id]||'(ยังไม่ตอบ)'}`).join('\n\n---\n\n');try{await navigator.clipboard.writeText(t);alert('คัดลอกแล้ว')}catch{prompt('คัดลอก:',t)}};
$('#note').onclick=()=>window.open('./short-note.html','_blank');
window.addEventListener('load',()=>{load();tabs();render()});