/* Exact stdin -> stdout judge. No hidden driver. */
let exactResults={};
const X={
'ชุด 1':{
21:{p:`เขียนโปรแกรม Python เรื่อง <b>Class และ Object</b><br>1. สร้าง class <code>Student</code><br>2. สร้าง object 2 ตัว<br>3. รับชื่อมหาวิทยาลัยของ object ตัวที่ 1 และตัวที่ 2 จาก input คนละบรรทัด<br>4. กำหนดค่าให้ object ทั้งสอง<br>5. แสดงผลตาม Testcase โดย <b>ทุกตัวอักษรต้องตรงกัน</b><br><br><b>การตรวจ:</b> ระบบป้อน input ผ่าน stdin แล้วรันโปรแกรมของคุณเองตั้งแต่ต้นจนจบ ไม่มี hidden driver`,t:[['ABC\nKMITL\n','*** Student Class ***\ns1.university : ABC\ns2.university : KMITL\n===== End of program =====\n'],['KMITL\nKMITL\n','*** Student Class ***\ns1.university : KMITL\ns2.university : KMITL\n===== End of program =====\n'],['MIT\nStanford\n','*** Student Class ***\ns1.university : MIT\ns2.university : Stanford\n===== End of program =====\n']]},
22:{p:`เขียนโปรแกรม Python เพื่อแสดง <b>Class Attribute และ Object Property</b><br>สร้าง class <code>A</code> ที่มี <code>x = 1</code>, รับ integer 1 ค่า, แสดงค่าก่อน shadow, หลัง shadow, ค่า class และหลัง <code>del a.x</code> ตาม Testcase ทุกตัวอักษร`,t:[['9\n','*** Attribute Lookup ***\nBefore shadow : 1\nAfter shadow : 9\nClass x : 1\nAfter del : 1\n===== End of program =====\n'],['25\n','*** Attribute Lookup ***\nBefore shadow : 1\nAfter shadow : 25\nClass x : 1\nAfter del : 1\n===== End of program =====\n']]},
25:{p:`เขียนโปรแกรม Python ที่ใช้ class <code>Device</code> มี class attribute <code>category = 'sensor'</code>, สร้าง d1/d2, รับชื่อ 2 ค่าและแสดงผลตาม Testcase ทุกตัวอักษร`,t:[['A\nB\n','*** Device Objects ***\ncategory : sensor\nd1.name : A\nd2.name : B\n===== End of program =====\n'],['Temp\nPressure\n','*** Device Objects ***\ncategory : sensor\nd1.name : Temp\nd2.name : Pressure\n===== End of program =====\n']]}
},
'ชุด 2':{
21:{p:`เขียนโปรแกรม Python เพื่อสาธิตการเปลี่ยน <b>Class Attribute</b> โดยสร้าง class A ที่มี x=1, objects a/b, รับ integer 1 ค่าไปกำหนด A.x แล้วแสดง a.x, b.x, A.x ตาม Testcase ทุกตัวอักษร`,t:[['7\n','*** Class Attribute ***\na.x : 7\nb.x : 7\nA.x : 7\n===== End of program =====\n'],['100\n','*** Class Attribute ***\na.x : 100\nb.x : 100\nA.x : 100\n===== End of program =====\n']]},
22:{p:`เขียนโปรแกรม Python เพื่อสาธิต <b>Instance Shadowing</b> โดย class A มี x=1, สร้าง a/b, รับ integer ไปกำหนด a.x และแสดง a.x, b.x, A.x ตาม Testcase ทุกตัวอักษร`,t:[['9\n','*** Shadowing ***\na.x : 9\nb.x : 1\nA.x : 1\n===== End of program =====\n'],['-5\n','*** Shadowing ***\na.x : -5\nb.x : 1\nA.x : 1\n===== End of program =====\n']]},
23:{p:`เขียนโปรแกรม Python ที่มี class <code>Box</code>, method <code>set_value(self,v)</code> และ <code>show(self)</code>, รับ integer 2 ค่าแล้วแสดงผลหลัง set แต่ละครั้งตาม Testcase ทุกตัวอักษร`,t:[['10\n25\n','*** Box Methods ***\nshow : 10\nshow : 25\n===== End of program =====\n'],['-3\n0\n','*** Box Methods ***\nshow : -3\nshow : 0\n===== End of program =====\n']]}
},
'ชุด 3':{
21:{p:`เขียนโปรแกรม Python ที่สร้าง object 2 ตัวจาก class เดียวกัน รับ integer 2 ค่าไปกำหนด a.value และ b.value แล้วแสดงผลตาม Testcase ทุกตัวอักษร`,t:[['1\n2\n','*** Object State ***\na.value : 1\nb.value : 2\n===== End of program =====\n'],['100\n-50\n','*** Object State ***\na.value : 100\nb.value : -50\n===== End of program =====\n']]},
23:{p:`เขียนโปรแกรม Python ที่มี class <code>Score</code>, class attribute <code>value=0</code>, methods set/show, สร้าง s1/s2, รับ integer 1 ค่าไป set เฉพาะ s1 แล้วแสดงผลตาม Testcase ทุกตัวอักษร`,t:[['9\n','*** Score Class ***\ns1 : 9\ns2 : 0\n===== End of program =====\n'],['100\n','*** Score Class ***\ns1 : 100\ns2 : 0\n===== End of program =====\n']]},
24:{p:`เขียนโปรแกรม Python เพื่อแสดง alias โดยสร้าง class A, a=A(), b=a, รับ integer ไปกำหนด a.x, ลบด้วย del b.x แล้วแสดง a is b และ hasattr(a,'x') ตาม Testcase ทุกตัวอักษร`,t:[['1\n','*** Object Alias ***\na is b : True\na has x : False\n===== End of program =====\n'],['999\n','*** Object Alias ***\na is b : True\na has x : False\n===== End of program =====\n']]},
25:{p:`เขียนโปรแกรม Python ที่รวม Class Attribute, Method, Object Properties และ Alias โดยใช้ class Item, category='general', method show(), objects i1/i2 และ ref=i1 แล้วแสดงผลตาม Testcase ทุกตัวอักษร`,t:[['A2\nB\n','*** Item Class ***\ncategory : general\ni1.show() : A2\ni2.show() : B\nref is i1 : True\n===== End of program =====\n'],['Book\nPen\n','*** Item Class ***\ncategory : general\ni1.show() : Book\ni2.show() : Pen\nref is i1 : True\n===== End of program =====\n']]}
}};
for(const [sn,items] of Object.entries(X)){for(const [id,m] of Object.entries(items)){const q=DATA[sn].written.find(x=>x.id===+id);if(q){q.prompt=m.p;q.codeRequired=true;q.testCases=m.t.map(([input,expected])=>({input,expected}));}}}
const _l=load;load=function(){_l();try{exactResults=JSON.parse(localStorage.getItem(key('exacttests'))||'{}')}catch{exactResults={}}};
const _s=save;save=function(){_s();localStorage.setItem(key('exacttests'),JSON.stringify(exactResults))};
function panel(q){const rs=exactResults[q.id]||[];return `<div class="sample-tests"><div style="display:flex;justify-content:space-between;align-items:center"><h3>Testcases</h3><button class="run-all" data-exact-run="${q.id}">▶ Run</button></div>${q.testCases.map((t,i)=>{const r=rs[i];return `<div class="sample-case${!r?'':r.pass?' pass':' fail'}"><div class="sample-title">Testcase : #${i+1}</div><div style="padding:14px 18px 0;color:#111"><b>Input</b></div><pre class="sample-terminal">${esc(t.input)}</pre><div style="padding:0 18px;color:#111"><b>Expected Output</b></div><pre class="sample-terminal">${esc(t.expected)}</pre>${r?`<div class="result-block"><div class="result-label">Result</div><pre class="sample-terminal sample-actual">${esc(r.actual??'')}</pre><div class="${r.pass?'sample-ok':'sample-ng'} result-status">${r.pass?'✅ ตรงกับ Testcase ทุกตัวอักษร':'❌ ไม่ตรงกับ Testcase'}</div></div>`:''}</div>`}).join('')}<div style="color:var(--muted);font-size:12px">Exact match: space, เครื่องหมาย, ตัวพิมพ์เล็ก/ใหญ่ และ newline ต้องตรงทั้งหมด</div></div>`}
const _w=wr;wr=function(q){if(!q.codeRequired)return _w(q);const g=submitted?grade(q,wa[q.id]):null,rs=exactResults[q.id]||[],pass=rs.filter(x=>x&&x.pass).length;return `<section class="card" id="q${q.id}"><div class="qhead"><b>ข้อ ${q.id}</b><span>${q.topic} · ${q.difficulty}</span></div><div class="written-question"><span class="label">โจทย์</span><div class="prompt">${q.prompt}</div></div><div style="margin-top:12px"><b>โค้ด Python</b><textarea class="code-editor" data-code-id="${q.id}" placeholder="# เขียนโปรแกรม Python ที่นี่...">${codeAns[q.id]||''}</textarea></div>${panel(q)}<div style="margin-top:12px"><b>คำตอบ / คำอธิบาย</b><textarea data-exp-id="${q.id}" ${submitted?'readonly':''}>${wa[q.id]||''}</textarea></div>${submitted?`<div class="grade"><b>Testcases:</b> ${pass}/${q.testCases.length} passed</div>${badge(g)}<div class="solution"><b>แนวคำตอบ</b><br>${q.solution}</div>`:''}</section>`};
const _b=bind;bind=function(){_b();document.querySelectorAll('[data-code-id]').forEach(x=>x.oninput=()=>{const id=+x.dataset.codeId;codeAns[id]=x.value;exactResults[id]=[];save();prog();nav()});document.querySelectorAll('[data-exact-run]').forEach(b=>b.onclick=()=>runExact(+b.dataset.exactRun,b))};
async function cap(code,input,btn){const py=await ensurePyodide(btn);py.globals.set('USER_CODE',code);py.globals.set('INPUT_TEXT',input||'');await py.runPythonAsync("compile(USER_CODE, '<student>', 'exec')");return String(await py.runPythonAsync(`import sys,io,traceback\nbuf=io.StringIO()\ni,o,e=sys.stdin,sys.stdout,sys.stderr\nsys.stdin=io.StringIO(INPUT_TEXT);sys.stdout=buf;sys.stderr=buf\ntry:\n exec(USER_CODE,{})\nexcept Exception:\n traceback.print_exc()\nfinally:\n sys.stdin,sys.stdout,sys.stderr=i,o,e\nbuf.getvalue()`)).replace(/\r\n/g,'\n')}
async function runExact(id,btn){const q=DATA[setName].written.find(x=>x.id===id),code=codeAns[id]||'';if(!code.trim()){alert('กรุณาเขียนโค้ดก่อนกด Run');return}const bad=unsafe(code);if(bad){alert(bad);return}const old=btn.textContent,rs=[];btn.disabled=true;btn.textContent='กำลังรัน...';try{for(const t of q.testCases){try{const actual=await cap(code,t.input,btn),expected=String(t.expected).replace(/\r\n/g,'\n');rs.push({pass:actual===expected,actual})}catch(err){rs.push({pass:false,actual:String(err)})}}exactResults[id]=rs;save();render()}finally{btn.disabled=false;btn.textContent=old}}
const _r=$('#reset').onclick;$('#reset').onclick=()=>{localStorage.removeItem(key('exacttests'));exactResults={};_r()};